Repository dhq-le/CITS3403-Project, pull requests merged in 2025-05, with the labels that each got.

#23 Signin page
  app/__init__.py
  app/blueprints.py
  app/config.py
  app/controllers.py
  app/database.db
  app/forms.py
  app/models.py
  app/routes.py
  app/static/css/login.css
  app/static/logo.jpg
  app/templates/login.html
  app/templates/signup.html
  init_db.py
  requirements.txt
  run.py
Labels: enhancement

#30 Fixed bug where users had same caloriesburnedgraph
  app/controllers.py
Labels: bug

#42 hotfix for the login validator.
  app/forms.py
Labels: bug

#44 Security implemntation
  .env
  .gitignore
  app/__init__.py
  app/config.py
  app/controllers.py
  app/database.db
  app/forms.py
  app/models.py
  app/templates/home.html
  requirements.txt
Labels: documentation

#48 Loginpage prttify
  app/static/css/login.css
  app/static/images/bg.jpeg
  app/static/js/friends.js
  app/templates/friends.html
  app/templates/login.html
  app/templates/signup.html
Labels: enhancement

#47 Selenium Testing
  app/__init__.py
  app/config.py
  app/forms.py
  selenium_tests.py
Labels: documentation

#55 Reverting BetterVersion
  app/static/css/friends.css
  app/static/css/login.css
  app/static/images/bg.jpeg
  app/static/images/tricepPress1.jpg
  app/static/images/tricepPress2.jpg
  app/templates/base.html
  app/templates/exercise.html
  app/templates/friends.html
  app/templates/signup.html
Labels: bug, documentation, enhancement

#57 Small edit in Selenium testing
  selenium_tests.py
Labels: bug

#62 Moved directory and update
  .DS_Store
  app/database.db
  tests/selenium_tests.py
Labels: enhancement

#73 Caloriesburntdate
  app/controllers.py
  app/static/css/base.css
  app/static/css/homepage.css
  app/static/js/caloriesburnt.js
  app/static/js/friends.js
  app/templates/friends.html
  app/templates/home.html
  app/templates/profile.html
Labels: bug, enhancement
